// Generated by `every_declaration_this_file_reads_is_pinned_for_tsc` in
// crates/verus-wasm/src/types.rs. Do not edit: that test rewrites this file
// when run with UPDATE_TYPESCRIPT_PINS=1, and fails when the two disagree.
//
// # What this is for
//
// The Rust drift guards read `types.d.ts` with a small parser, and a parser
// that is wrong in a caller's favour is the whole failure mode this design
// exists to rule out: five adversarial rounds against the previous version all
// worked by making a deleted registration still *look* present to a scan. The
// parser here is not trusted either. Instead it writes down everything it
// believes, and tsc — which reads the same file for real, comments and all —
// is made to check it.
//
// So a member of an interface that a block comment hides from tsc but not from
// the parser lands here as a member tsc cannot find, and the compiler says so.
// Same for a member the parser reads with the wrong declared type, and for one
// it reads as required that ships optional.
//
// # Reading a failure
//
// `TS2344: Type 'false' does not satisfy the constraint 'true'` on a line below
// means the parser and tsc disagree about that exact line's claim; the line
// names the interface and, for a member, the member. `TS2339: Property 'x' does
// not exist` means the parser saw a member tsc does not.
//
// Nothing imports this file: `tsc --noEmit` is the whole test, and .github/
// workflows/ci.yml names it in the same step as the other declaration checks.

import type {
  CommitmentExpired,
  CommitmentGone,
  CommitmentReady,
  CommitmentReorged,
  CommitmentStatus,
  CommitmentStatusStep,
  CommitmentWaiting,
  Content,
  ContentRequest,
  ContentStep,
  ContentValue,
  ConvertRequest,
  CurrencyDefinition,
  DecodedIdentityCommitment,
  DecodedIdentityPayment,
  DecodedIdentityPrimary,
  DecodedInput,
  DecodedOutput,
  DecodedPubKey,
  DecodedPubKeyHash,
  DecodedReserveDeposit,
  DecodedReserveOutput,
  DecodedReserveTransfer,
  DecodedTransaction,
  DecodedTxOut,
  DecodedUnknown,
  DecodedUnsupportedCryptoCondition,
  Demand,
  DemandNative,
  DemandToken,
  Funding,
  HistoryEntry,
  HistoryRequest,
  HistoryStep,
  LaunchStep,
  Launched,
  Listing,
  LoggedIn,
  LoginRequest,
  LoginStep,
  MnemonicCheck,
  OfferSide,
  OfferSideCurrencies,
  OfferSideIdentity,
  OfferTerms,
  OfferTermsRequest,
  OfferTermsStep,
  OffersRequest,
  OffersStep,
  Outpoint,
  Pending,
  PendingRequest,
  PlanBurnRequest,
  PlanConvertFromIdentityRequest,
  PlanConvertRequest,
  PlanLaunchRequest,
  PlanMintRequest,
  PlanPublishRequest,
  PlanRegistrationRequest,
  PlanSendFromIdentityRequest,
  PlanSendRequest,
  PlanSendTokenFromIdentityRequest,
  PlanSendTokenRequest,
  PlanStep,
  PlanStepAsk,
  PlanStepReady,
  PlannedTransaction,
  PlannedUpdate,
  Preallocation,
  Recipient,
  Registered,
  RegisteredStep,
  RegistrationStep,
  Requests,
  SendRequest,
  SignRequest,
  SignedTransaction,
  SpendableRequest,
  SpendableStep,
  TakeOfferRequest,
  TakeOfferStep,
  Taken,
  TokenAmount,
  TokenRecipient,
  TokenSendRequest,
  TransactionStep,
  UpdateStep,
  Utxo,
  VerifyLoginRequest,
  VerifyLoginStep,
  VerifyRequest,
  VerifyResult,
} from "../../pkg/verus_wasm.js";

/** Two types, neither wider than the other. Wrapped in tuples so a union is compared whole rather than distributed member by member. */
type Exact<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

/** Fails to instantiate unless what it is given is `true`, which is how a disagreement becomes a compile error rather than an unread type. */
type Agrees<T extends true> = T;

/** The members declared with a `?`. `keyof` alone cannot tell them apart. */
type OptionalKeys<T> = { [K in keyof T]-?: {} extends Pick<T, K> ? K : never }[keyof T];

type _Utxo = [
  Agrees<Exact<keyof Utxo, "satoshis" | "scriptPubKey" | "txid" | "vout">>,
  Agrees<Exact<OptionalKeys<Utxo>, never>>,
  Agrees<Exact<Required<Utxo>["satoshis"], string>>,
  Agrees<Exact<Required<Utxo>["scriptPubKey"], string>>,
  Agrees<Exact<Required<Utxo>["txid"], string>>,
  Agrees<Exact<Required<Utxo>["vout"], number>>,
];

type _Recipient = [
  Agrees<Exact<keyof Recipient, "address" | "satoshis">>,
  Agrees<Exact<OptionalKeys<Recipient>, never>>,
  Agrees<Exact<Required<Recipient>["address"], string>>,
  Agrees<Exact<Required<Recipient>["satoshis"], string>>,
];

type _TokenRecipient = [
  Agrees<Exact<keyof TokenRecipient, "address" | "amount" | "currency">>,
  Agrees<Exact<OptionalKeys<TokenRecipient>, never>>,
  Agrees<Exact<Required<TokenRecipient>["address"], string>>,
  Agrees<Exact<Required<TokenRecipient>["amount"], string>>,
  Agrees<Exact<Required<TokenRecipient>["currency"], string>>,
];

type _SendRequest = [
  Agrees<Exact<keyof SendRequest, "changeAddress" | "expiryHeight" | "feePerKb" | "recipients" | "utxos">>,
  Agrees<Exact<OptionalKeys<SendRequest>, "expiryHeight" | "feePerKb">>,
  Agrees<Exact<Required<SendRequest>["changeAddress"], string>>,
  Agrees<Exact<Required<SendRequest>["expiryHeight"], number | null>>,
  Agrees<Exact<Required<SendRequest>["feePerKb"], string | null>>,
  Agrees<Exact<Required<SendRequest>["recipients"], Recipient[]>>,
  Agrees<Exact<Required<SendRequest>["utxos"], Utxo[]>>,
];

type _TokenSendRequest = [
  Agrees<Exact<keyof TokenSendRequest, "changeAddress" | "expiryHeight" | "feePerKb" | "recipients" | "utxos">>,
  Agrees<Exact<OptionalKeys<TokenSendRequest>, "expiryHeight" | "feePerKb">>,
  Agrees<Exact<Required<TokenSendRequest>["changeAddress"], string>>,
  Agrees<Exact<Required<TokenSendRequest>["expiryHeight"], number | null>>,
  Agrees<Exact<Required<TokenSendRequest>["feePerKb"], string | null>>,
  Agrees<Exact<Required<TokenSendRequest>["recipients"], TokenRecipient[]>>,
  Agrees<Exact<Required<TokenSendRequest>["utxos"], Utxo[]>>,
];

type _ConvertRequest = [
  Agrees<Exact<keyof ConvertRequest, "amount" | "chainCurrency" | "changeAddress" | "expiryHeight" | "fee" | "feeCurrency" | "feePerKb" | "from" | "into" | "kind" | "recipient" | "refund" | "tokenFunding" | "utxos" | "via">>,
  Agrees<Exact<OptionalKeys<ConvertRequest>, "expiryHeight" | "feeCurrency" | "feePerKb" | "refund" | "tokenFunding" | "via">>,
  Agrees<Exact<Required<ConvertRequest>["amount"], string>>,
  Agrees<Exact<Required<ConvertRequest>["chainCurrency"], string>>,
  Agrees<Exact<Required<ConvertRequest>["changeAddress"], string>>,
  Agrees<Exact<Required<ConvertRequest>["expiryHeight"], number | null>>,
  Agrees<Exact<Required<ConvertRequest>["fee"], string>>,
  Agrees<Exact<Required<ConvertRequest>["feeCurrency"], string | null>>,
  Agrees<Exact<Required<ConvertRequest>["feePerKb"], string | null>>,
  Agrees<Exact<Required<ConvertRequest>["from"], string>>,
  Agrees<Exact<Required<ConvertRequest>["into"], string>>,
  Agrees<Exact<Required<ConvertRequest>["kind"], "intoFractional" | "intoReserve" | "reserveToReserve" | "preconvert">>,
  Agrees<Exact<Required<ConvertRequest>["recipient"], string>>,
  Agrees<Exact<Required<ConvertRequest>["refund"], string | null>>,
  Agrees<Exact<Required<ConvertRequest>["tokenFunding"], Utxo[] | null>>,
  Agrees<Exact<Required<ConvertRequest>["utxos"], Utxo[]>>,
  Agrees<Exact<Required<ConvertRequest>["via"], string | null>>,
];

type _Outpoint = [
  Agrees<Exact<keyof Outpoint, "txid" | "vout">>,
  Agrees<Exact<OptionalKeys<Outpoint>, never>>,
  Agrees<Exact<Required<Outpoint>["txid"], string>>,
  Agrees<Exact<Required<Outpoint>["vout"], number>>,
];

type _SignedTransaction = [
  Agrees<Exact<keyof SignedTransaction, "change" | "fee" | "hex" | "inputsUsed" | "txid">>,
  Agrees<Exact<OptionalKeys<SignedTransaction>, never>>,
  Agrees<Exact<Required<SignedTransaction>["change"], string>>,
  Agrees<Exact<Required<SignedTransaction>["fee"], string>>,
  Agrees<Exact<Required<SignedTransaction>["hex"], string>>,
  Agrees<Exact<Required<SignedTransaction>["inputsUsed"], Outpoint[]>>,
  Agrees<Exact<Required<SignedTransaction>["txid"], string>>,
];

type _SignRequest = [
  Agrees<Exact<keyof SignRequest, "blockHeight" | "existing" | "identity" | "message" | "systemId">>,
  Agrees<Exact<OptionalKeys<SignRequest>, "existing">>,
  Agrees<Exact<Required<SignRequest>["blockHeight"], number>>,
  Agrees<Exact<Required<SignRequest>["existing"], string | null>>,
  Agrees<Exact<Required<SignRequest>["identity"], string>>,
  Agrees<Exact<Required<SignRequest>["message"], string>>,
  Agrees<Exact<Required<SignRequest>["systemId"], string>>,
];

type _VerifyRequest = [
  Agrees<Exact<keyof VerifyRequest, "currentHeight" | "identity" | "maxAgeBlocks" | "message" | "minimumSignatures" | "primaryAddresses" | "signature" | "systemId">>,
  Agrees<Exact<OptionalKeys<VerifyRequest>, never>>,
  Agrees<Exact<Required<VerifyRequest>["currentHeight"], number>>,
  Agrees<Exact<Required<VerifyRequest>["identity"], string>>,
  Agrees<Exact<Required<VerifyRequest>["maxAgeBlocks"], number>>,
  Agrees<Exact<Required<VerifyRequest>["message"], string>>,
  Agrees<Exact<Required<VerifyRequest>["minimumSignatures"], number>>,
  Agrees<Exact<Required<VerifyRequest>["primaryAddresses"], string[]>>,
  Agrees<Exact<Required<VerifyRequest>["signature"], string>>,
  Agrees<Exact<Required<VerifyRequest>["systemId"], string>>,
];

type _VerifyResult = [
  Agrees<Exact<keyof VerifyResult, "blockHeight" | "reason" | "signers" | "valid">>,
  Agrees<Exact<OptionalKeys<VerifyResult>, "reason">>,
  Agrees<Exact<Required<VerifyResult>["blockHeight"], number>>,
  Agrees<Exact<Required<VerifyResult>["reason"], "stale" | "future" | "threshold">>,
  Agrees<Exact<Required<VerifyResult>["signers"], string[]>>,
  Agrees<Exact<Required<VerifyResult>["valid"], boolean>>,
];

type _TokenAmount = [
  Agrees<Exact<keyof TokenAmount, "amount" | "currency">>,
  Agrees<Exact<OptionalKeys<TokenAmount>, never>>,
  Agrees<Exact<Required<TokenAmount>["amount"], string>>,
  Agrees<Exact<Required<TokenAmount>["currency"], string>>,
];

type _MnemonicCheck = [
  Agrees<Exact<keyof MnemonicCheck, "position" | "reason" | "valid" | "words">>,
  Agrees<Exact<OptionalKeys<MnemonicCheck>, "position" | "reason">>,
  Agrees<Exact<Required<MnemonicCheck>["position"], number>>,
  Agrees<Exact<Required<MnemonicCheck>["reason"], "wordCount" | "unknownWord" | "checksum">>,
  Agrees<Exact<Required<MnemonicCheck>["valid"], boolean>>,
  Agrees<Exact<Required<MnemonicCheck>["words"], number>>,
];

type _DecodedTransaction = [
  Agrees<Exact<keyof DecodedTransaction, "expiryHeight" | "inputs" | "lockTime" | "outputs" | "shielded" | "txid" | "valueBalance">>,
  Agrees<Exact<OptionalKeys<DecodedTransaction>, never>>,
  Agrees<Exact<Required<DecodedTransaction>["expiryHeight"], number>>,
  Agrees<Exact<Required<DecodedTransaction>["inputs"], DecodedInput[]>>,
  Agrees<Exact<Required<DecodedTransaction>["lockTime"], number>>,
  Agrees<Exact<Required<DecodedTransaction>["outputs"], DecodedTxOut[]>>,
  Agrees<Exact<Required<DecodedTransaction>["shielded"], boolean>>,
  Agrees<Exact<Required<DecodedTransaction>["txid"], string>>,
  Agrees<Exact<Required<DecodedTransaction>["valueBalance"], string>>,
];

type _DecodedInput = [
  Agrees<Exact<keyof DecodedInput, "sequence" | "txid" | "vout">>,
  Agrees<Exact<OptionalKeys<DecodedInput>, never>>,
  Agrees<Exact<Required<DecodedInput>["sequence"], number>>,
  Agrees<Exact<Required<DecodedInput>["txid"], string>>,
  Agrees<Exact<Required<DecodedInput>["vout"], number>>,
];

type _DecodedTxOut = [
  Agrees<Exact<keyof DecodedTxOut, "output" | "satoshis" | "scriptPubKey">>,
  Agrees<Exact<OptionalKeys<DecodedTxOut>, never>>,
  Agrees<Exact<Required<DecodedTxOut>["output"], DecodedOutput>>,
  Agrees<Exact<Required<DecodedTxOut>["satoshis"], string>>,
  Agrees<Exact<Required<DecodedTxOut>["scriptPubKey"], string>>,
];

type _DecodedPubKeyHash = [
  Agrees<Exact<keyof DecodedPubKeyHash, "address" | "kind">>,
  Agrees<Exact<OptionalKeys<DecodedPubKeyHash>, never>>,
  Agrees<Exact<Required<DecodedPubKeyHash>["address"], string>>,
  Agrees<Exact<Required<DecodedPubKeyHash>["kind"], "pubKeyHash">>,
];

type _DecodedPubKey = [
  Agrees<Exact<keyof DecodedPubKey, "address" | "kind">>,
  Agrees<Exact<OptionalKeys<DecodedPubKey>, never>>,
  Agrees<Exact<Required<DecodedPubKey>["address"], string>>,
  Agrees<Exact<Required<DecodedPubKey>["kind"], "pubKey">>,
];

type _DecodedReserveOutput = [
  Agrees<Exact<keyof DecodedReserveOutput, "address" | "kind" | "tokens">>,
  Agrees<Exact<OptionalKeys<DecodedReserveOutput>, never>>,
  Agrees<Exact<Required<DecodedReserveOutput>["address"], string>>,
  Agrees<Exact<Required<DecodedReserveOutput>["kind"], "reserveOutput">>,
  Agrees<Exact<Required<DecodedReserveOutput>["tokens"], TokenAmount[]>>,
];

type _DecodedIdentityPayment = [
  Agrees<Exact<keyof DecodedIdentityPayment, "address" | "kind">>,
  Agrees<Exact<OptionalKeys<DecodedIdentityPayment>, never>>,
  Agrees<Exact<Required<DecodedIdentityPayment>["address"], string>>,
  Agrees<Exact<Required<DecodedIdentityPayment>["kind"], "identityPayment">>,
];

type _DecodedIdentityPrimary = [
  Agrees<Exact<keyof DecodedIdentityPrimary, "address" | "kind" | "minimumSignatures" | "name" | "primaryAddresses">>,
  Agrees<Exact<OptionalKeys<DecodedIdentityPrimary>, never>>,
  Agrees<Exact<Required<DecodedIdentityPrimary>["address"], string>>,
  Agrees<Exact<Required<DecodedIdentityPrimary>["kind"], "identityPrimary">>,
  Agrees<Exact<Required<DecodedIdentityPrimary>["minimumSignatures"], number>>,
  Agrees<Exact<Required<DecodedIdentityPrimary>["name"], string>>,
  Agrees<Exact<Required<DecodedIdentityPrimary>["primaryAddresses"], string[]>>,
];

type _DecodedIdentityCommitment = [
  Agrees<Exact<keyof DecodedIdentityCommitment, "address" | "commitment" | "kind" | "tokens">>,
  Agrees<Exact<OptionalKeys<DecodedIdentityCommitment>, never>>,
  Agrees<Exact<Required<DecodedIdentityCommitment>["address"], string>>,
  Agrees<Exact<Required<DecodedIdentityCommitment>["commitment"], string>>,
  Agrees<Exact<Required<DecodedIdentityCommitment>["kind"], "identityCommitment">>,
  Agrees<Exact<Required<DecodedIdentityCommitment>["tokens"], TokenAmount[]>>,
];

type _DecodedReserveDeposit = [
  Agrees<Exact<keyof DecodedReserveDeposit, "address" | "controllingCurrency" | "kind" | "tokens">>,
  Agrees<Exact<OptionalKeys<DecodedReserveDeposit>, never>>,
  Agrees<Exact<Required<DecodedReserveDeposit>["address"], string>>,
  Agrees<Exact<Required<DecodedReserveDeposit>["controllingCurrency"], string>>,
  Agrees<Exact<Required<DecodedReserveDeposit>["kind"], "reserveDeposit">>,
  Agrees<Exact<Required<DecodedReserveDeposit>["tokens"], TokenAmount[]>>,
];

type _DecodedReserveTransfer = [
  Agrees<Exact<keyof DecodedReserveTransfer, "address" | "destinationCurrency" | "feeCurrency" | "fees" | "flags" | "kind" | "recipient" | "tokens">>,
  Agrees<Exact<OptionalKeys<DecodedReserveTransfer>, never>>,
  Agrees<Exact<Required<DecodedReserveTransfer>["address"], string>>,
  Agrees<Exact<Required<DecodedReserveTransfer>["destinationCurrency"], string>>,
  Agrees<Exact<Required<DecodedReserveTransfer>["feeCurrency"], string>>,
  Agrees<Exact<Required<DecodedReserveTransfer>["fees"], string>>,
  Agrees<Exact<Required<DecodedReserveTransfer>["flags"], number>>,
  Agrees<Exact<Required<DecodedReserveTransfer>["kind"], "reserveTransfer">>,
  Agrees<Exact<Required<DecodedReserveTransfer>["recipient"], string>>,
  Agrees<Exact<Required<DecodedReserveTransfer>["tokens"], TokenAmount[]>>,
];

type _DecodedUnsupportedCryptoCondition = [
  Agrees<Exact<keyof DecodedUnsupportedCryptoCondition, "evalCode" | "kind" | "mayCarryCurrency">>,
  Agrees<Exact<OptionalKeys<DecodedUnsupportedCryptoCondition>, never>>,
  Agrees<Exact<Required<DecodedUnsupportedCryptoCondition>["evalCode"], number>>,
  Agrees<Exact<Required<DecodedUnsupportedCryptoCondition>["kind"], "unsupportedCryptoCondition">>,
  Agrees<Exact<Required<DecodedUnsupportedCryptoCondition>["mayCarryCurrency"], boolean>>,
];

type _DecodedUnknown = [
  Agrees<Exact<keyof DecodedUnknown, "kind">>,
  Agrees<Exact<OptionalKeys<DecodedUnknown>, never>>,
  Agrees<Exact<Required<DecodedUnknown>["kind"], "unknown">>,
];

type _PlanSendRequest = [
  Agrees<Exact<keyof PlanSendRequest, "satoshis" | "to">>,
  Agrees<Exact<OptionalKeys<PlanSendRequest>, never>>,
  Agrees<Exact<Required<PlanSendRequest>["satoshis"], string>>,
  Agrees<Exact<Required<PlanSendRequest>["to"], string>>,
];

type _PlannedTransaction = [
  Agrees<Exact<keyof PlannedTransaction, "change" | "fee" | "hex" | "txid">>,
  Agrees<Exact<OptionalKeys<PlannedTransaction>, never>>,
  Agrees<Exact<Required<PlannedTransaction>["change"], string>>,
  Agrees<Exact<Required<PlannedTransaction>["fee"], string>>,
  Agrees<Exact<Required<PlannedTransaction>["hex"], string>>,
  Agrees<Exact<Required<PlannedTransaction>["txid"], string>>,
];

type _PlanStepAsk = [
  Agrees<Exact<keyof PlanStepAsk, "ask" | "kind">>,
  Agrees<Exact<OptionalKeys<PlanStepAsk>, never>>,
  Agrees<Exact<Required<PlanStepAsk>["ask"], string[]>>,
  Agrees<Exact<Required<PlanStepAsk>["kind"], "ask">>,
];

type _PlanStepReady = [
  Agrees<Exact<keyof PlanStepReady<any>, "ask" | "kind" | "value">>,
  Agrees<Exact<OptionalKeys<PlanStepReady<any>>, never>>,
  // Member types are left unpinned here: they may name this interface's own
  // type parameters, which mean nothing outside it. Its member names and
  // their optionality are pinned above like everybody else's.
];

type _HistoryRequest = [
  Agrees<Exact<keyof HistoryRequest, "addresses" | "endHeight" | "startHeight">>,
  Agrees<Exact<OptionalKeys<HistoryRequest>, "endHeight" | "startHeight">>,
  Agrees<Exact<Required<HistoryRequest>["addresses"], string[]>>,
  Agrees<Exact<Required<HistoryRequest>["endHeight"], number>>,
  Agrees<Exact<Required<HistoryRequest>["startHeight"], number>>,
];

type _HistoryEntry = [
  Agrees<Exact<keyof HistoryEntry, "blockIndex" | "blockTime" | "height" | "netCurrencies" | "netNative" | "spentSomething" | "txid">>,
  Agrees<Exact<OptionalKeys<HistoryEntry>, never>>,
  Agrees<Exact<Required<HistoryEntry>["blockIndex"], number>>,
  Agrees<Exact<Required<HistoryEntry>["blockTime"], number>>,
  Agrees<Exact<Required<HistoryEntry>["height"], number>>,
  Agrees<Exact<Required<HistoryEntry>["netCurrencies"], Record<string, string>>>,
  Agrees<Exact<Required<HistoryEntry>["netNative"], string>>,
  Agrees<Exact<Required<HistoryEntry>["spentSomething"], boolean>>,
  Agrees<Exact<Required<HistoryEntry>["txid"], string>>,
];

type _LoginRequest = [
  Agrees<Exact<keyof LoginRequest, "audience" | "challenge">>,
  Agrees<Exact<OptionalKeys<LoginRequest>, never>>,
  Agrees<Exact<Required<LoginRequest>["audience"], string>>,
  Agrees<Exact<Required<LoginRequest>["challenge"], string>>,
];

type _VerifyLoginRequest = [
  Agrees<Exact<keyof VerifyLoginRequest, "audience" | "challenge" | "identity" | "maxAgeBlocks" | "maxFutureBlocks" | "signature">>,
  Agrees<Exact<OptionalKeys<VerifyLoginRequest>, "maxAgeBlocks" | "maxFutureBlocks">>,
  Agrees<Exact<Required<VerifyLoginRequest>["audience"], string>>,
  Agrees<Exact<Required<VerifyLoginRequest>["challenge"], string>>,
  Agrees<Exact<Required<VerifyLoginRequest>["identity"], string>>,
  Agrees<Exact<Required<VerifyLoginRequest>["maxAgeBlocks"], number>>,
  Agrees<Exact<Required<VerifyLoginRequest>["maxFutureBlocks"], number>>,
  Agrees<Exact<Required<VerifyLoginRequest>["signature"], string>>,
];

type _LoggedIn = [
  Agrees<Exact<keyof LoggedIn, "identityAddress" | "name" | "signedAt" | "signers">>,
  Agrees<Exact<OptionalKeys<LoggedIn>, never>>,
  Agrees<Exact<Required<LoggedIn>["identityAddress"], string>>,
  Agrees<Exact<Required<LoggedIn>["name"], string>>,
  Agrees<Exact<Required<LoggedIn>["signedAt"], number>>,
  Agrees<Exact<Required<LoggedIn>["signers"], string[]>>,
];

type _SpendableRequest = [
  Agrees<Exact<keyof SpendableRequest, "address">>,
  Agrees<Exact<OptionalKeys<SpendableRequest>, never>>,
  Agrees<Exact<Required<SpendableRequest>["address"], string>>,
];

type _Funding = [
  Agrees<Exact<keyof Funding, "notYetSpendable" | "other" | "spentUnconfirmed" | "tip" | "total" | "utxos">>,
  Agrees<Exact<OptionalKeys<Funding>, never>>,
  Agrees<Exact<Required<Funding>["notYetSpendable"], string>>,
  Agrees<Exact<Required<Funding>["other"], number>>,
  Agrees<Exact<Required<Funding>["spentUnconfirmed"], string>>,
  Agrees<Exact<Required<Funding>["tip"], number>>,
  Agrees<Exact<Required<Funding>["total"], string>>,
  Agrees<Exact<Required<Funding>["utxos"], Utxo[]>>,
];

type _ContentRequest = [
  Agrees<Exact<keyof ContentRequest, "identity">>,
  Agrees<Exact<OptionalKeys<ContentRequest>, never>>,
  Agrees<Exact<Required<ContentRequest>["identity"], string>>,
];

type _ContentValue = [
  Agrees<Exact<keyof ContentValue, "hex" | "structured">>,
  Agrees<Exact<OptionalKeys<ContentValue>, "hex" | "structured">>,
  Agrees<Exact<Required<ContentValue>["hex"], string>>,
  Agrees<Exact<Required<ContentValue>["structured"], unknown>>,
];

type _PlanSendTokenRequest = [
  Agrees<Exact<keyof PlanSendTokenRequest, "amount" | "currency" | "to" | "tokenUtxos">>,
  Agrees<Exact<OptionalKeys<PlanSendTokenRequest>, never>>,
  Agrees<Exact<Required<PlanSendTokenRequest>["amount"], string>>,
  Agrees<Exact<Required<PlanSendTokenRequest>["currency"], string>>,
  Agrees<Exact<Required<PlanSendTokenRequest>["to"], string>>,
  Agrees<Exact<Required<PlanSendTokenRequest>["tokenUtxos"], Utxo[]>>,
];

type _PlanSendFromIdentityRequest = [
  Agrees<Exact<keyof PlanSendFromIdentityRequest, "identity" | "satoshis" | "to">>,
  Agrees<Exact<OptionalKeys<PlanSendFromIdentityRequest>, never>>,
  Agrees<Exact<Required<PlanSendFromIdentityRequest>["identity"], string>>,
  Agrees<Exact<Required<PlanSendFromIdentityRequest>["satoshis"], string>>,
  Agrees<Exact<Required<PlanSendFromIdentityRequest>["to"], string>>,
];

type _PlanSendTokenFromIdentityRequest = [
  Agrees<Exact<keyof PlanSendTokenFromIdentityRequest, "amount" | "currency" | "identity" | "to">>,
  Agrees<Exact<OptionalKeys<PlanSendTokenFromIdentityRequest>, never>>,
  Agrees<Exact<Required<PlanSendTokenFromIdentityRequest>["amount"], string>>,
  Agrees<Exact<Required<PlanSendTokenFromIdentityRequest>["currency"], string>>,
  Agrees<Exact<Required<PlanSendTokenFromIdentityRequest>["identity"], string>>,
  Agrees<Exact<Required<PlanSendTokenFromIdentityRequest>["to"], string>>,
];

type _PlanConvertFromIdentityRequest = [
  Agrees<Exact<keyof PlanConvertFromIdentityRequest, "amount" | "fee" | "from" | "identity" | "into" | "kind" | "recipient" | "via">>,
  Agrees<Exact<OptionalKeys<PlanConvertFromIdentityRequest>, "via">>,
  Agrees<Exact<Required<PlanConvertFromIdentityRequest>["amount"], string>>,
  Agrees<Exact<Required<PlanConvertFromIdentityRequest>["fee"], string>>,
  Agrees<Exact<Required<PlanConvertFromIdentityRequest>["from"], string>>,
  Agrees<Exact<Required<PlanConvertFromIdentityRequest>["identity"], string>>,
  Agrees<Exact<Required<PlanConvertFromIdentityRequest>["into"], string>>,
  Agrees<Exact<Required<PlanConvertFromIdentityRequest>["kind"], string>>,
  Agrees<Exact<Required<PlanConvertFromIdentityRequest>["recipient"], string>>,
  Agrees<Exact<Required<PlanConvertFromIdentityRequest>["via"], string>>,
];

type _PlanPublishRequest = [
  Agrees<Exact<keyof PlanPublishRequest, "identity" | "key" | "values">>,
  Agrees<Exact<OptionalKeys<PlanPublishRequest>, never>>,
  Agrees<Exact<Required<PlanPublishRequest>["identity"], string>>,
  Agrees<Exact<Required<PlanPublishRequest>["key"], string>>,
  Agrees<Exact<Required<PlanPublishRequest>["values"], string[]>>,
];

type _PlannedUpdate = [
  Agrees<Exact<keyof PlannedUpdate, "change" | "fee" | "hex" | "key" | "txid" | "values">>,
  Agrees<Exact<OptionalKeys<PlannedUpdate>, never>>,
  Agrees<Exact<Required<PlannedUpdate>["change"], string>>,
  Agrees<Exact<Required<PlannedUpdate>["fee"], string>>,
  Agrees<Exact<Required<PlannedUpdate>["hex"], string>>,
  Agrees<Exact<Required<PlannedUpdate>["key"], string>>,
  Agrees<Exact<Required<PlannedUpdate>["txid"], string>>,
  Agrees<Exact<Required<PlannedUpdate>["values"], number>>,
];

type _OffersRequest = [
  Agrees<Exact<keyof OffersRequest, "isCurrency" | "target" | "withOfferBytes">>,
  Agrees<Exact<OptionalKeys<OffersRequest>, "withOfferBytes">>,
  Agrees<Exact<Required<OffersRequest>["isCurrency"], boolean>>,
  Agrees<Exact<Required<OffersRequest>["target"], string>>,
  Agrees<Exact<Required<OffersRequest>["withOfferBytes"], boolean>>,
];

type _OfferSideCurrencies = [
  Agrees<Exact<keyof OfferSideCurrencies, "amounts" | "kind">>,
  Agrees<Exact<OptionalKeys<OfferSideCurrencies>, never>>,
  Agrees<Exact<Required<OfferSideCurrencies>["amounts"], Record<string, string>>>,
  Agrees<Exact<Required<OfferSideCurrencies>["kind"], "currencies">>,
];

type _OfferSideIdentity = [
  Agrees<Exact<keyof OfferSideIdentity, "identityId" | "kind" | "name" | "systemId">>,
  Agrees<Exact<OptionalKeys<OfferSideIdentity>, never>>,
  Agrees<Exact<Required<OfferSideIdentity>["identityId"], string>>,
  Agrees<Exact<Required<OfferSideIdentity>["kind"], "identity">>,
  Agrees<Exact<Required<OfferSideIdentity>["name"], string>>,
  Agrees<Exact<Required<OfferSideIdentity>["systemId"], string>>,
];

type _Listing = [
  Agrees<Exact<keyof Listing, "accepting" | "blockExpiry" | "bucket" | "fundingTxid" | "live" | "offering" | "price" | "rawOffer">>,
  Agrees<Exact<OptionalKeys<Listing>, "rawOffer">>,
  Agrees<Exact<Required<Listing>["accepting"], OfferSide>>,
  Agrees<Exact<Required<Listing>["blockExpiry"], number>>,
  Agrees<Exact<Required<Listing>["bucket"], string>>,
  Agrees<Exact<Required<Listing>["fundingTxid"], string>>,
  Agrees<Exact<Required<Listing>["live"], boolean>>,
  Agrees<Exact<Required<Listing>["offering"], OfferSide>>,
  Agrees<Exact<Required<Listing>["price"], string>>,
  Agrees<Exact<Required<Listing>["rawOffer"], string>>,
];

type _OfferTermsRequest = [
  Agrees<Exact<keyof OfferTermsRequest, "offer">>,
  Agrees<Exact<OptionalKeys<OfferTermsRequest>, never>>,
  Agrees<Exact<Required<OfferTermsRequest>["offer"], string>>,
];

type _DemandNative = [
  Agrees<Exact<keyof DemandNative, "amount" | "kind" | "recipient">>,
  Agrees<Exact<OptionalKeys<DemandNative>, never>>,
  Agrees<Exact<Required<DemandNative>["amount"], string>>,
  Agrees<Exact<Required<DemandNative>["kind"], "native">>,
  Agrees<Exact<Required<DemandNative>["recipient"], string>>,
];

type _DemandToken = [
  Agrees<Exact<keyof DemandToken, "amount" | "currency" | "kind" | "recipient">>,
  Agrees<Exact<OptionalKeys<DemandToken>, never>>,
  Agrees<Exact<Required<DemandToken>["amount"], string>>,
  Agrees<Exact<Required<DemandToken>["currency"], string>>,
  Agrees<Exact<Required<DemandToken>["kind"], "token">>,
  Agrees<Exact<Required<DemandToken>["recipient"], string>>,
];

type _OfferTerms = [
  Agrees<Exact<keyof OfferTerms, "confirmations" | "control" | "demand" | "expiryHeight" | "fundingTxid" | "fundingVout" | "offered">>,
  Agrees<Exact<OptionalKeys<OfferTerms>, never>>,
  Agrees<Exact<Required<OfferTerms>["confirmations"], number>>,
  Agrees<Exact<Required<OfferTerms>["control"], string>>,
  Agrees<Exact<Required<OfferTerms>["demand"], Demand>>,
  Agrees<Exact<Required<OfferTerms>["expiryHeight"], number>>,
  Agrees<Exact<Required<OfferTerms>["fundingTxid"], string>>,
  Agrees<Exact<Required<OfferTerms>["fundingVout"], number>>,
  Agrees<Exact<Required<OfferTerms>["offered"], string>>,
];

type _TakeOfferRequest = [
  Agrees<Exact<keyof TakeOfferRequest, "changeAddress" | "fee" | "offer" | "recipient" | "utxos">>,
  Agrees<Exact<OptionalKeys<TakeOfferRequest>, never>>,
  Agrees<Exact<Required<TakeOfferRequest>["changeAddress"], string>>,
  Agrees<Exact<Required<TakeOfferRequest>["fee"], string>>,
  Agrees<Exact<Required<TakeOfferRequest>["offer"], string>>,
  Agrees<Exact<Required<TakeOfferRequest>["recipient"], string>>,
  Agrees<Exact<Required<TakeOfferRequest>["utxos"], Utxo[]>>,
];

type _Taken = [
  Agrees<Exact<keyof Taken, "hex" | "terms" | "txid">>,
  Agrees<Exact<OptionalKeys<Taken>, never>>,
  Agrees<Exact<Required<Taken>["hex"], string>>,
  Agrees<Exact<Required<Taken>["terms"], OfferTerms>>,
  Agrees<Exact<Required<Taken>["txid"], string>>,
];

type _PlanConvertRequest = [
  Agrees<Exact<keyof PlanConvertRequest, "amount" | "fee" | "from" | "into" | "kind" | "minExpected" | "recipient" | "tokenFunding" | "via">>,
  Agrees<Exact<OptionalKeys<PlanConvertRequest>, "minExpected" | "tokenFunding" | "via">>,
  Agrees<Exact<Required<PlanConvertRequest>["amount"], string>>,
  Agrees<Exact<Required<PlanConvertRequest>["fee"], string>>,
  Agrees<Exact<Required<PlanConvertRequest>["from"], string>>,
  Agrees<Exact<Required<PlanConvertRequest>["into"], string>>,
  Agrees<Exact<Required<PlanConvertRequest>["kind"], "intoFractional" | "intoReserve" | "reserveToReserve" | "preconvert">>,
  Agrees<Exact<Required<PlanConvertRequest>["minExpected"], string>>,
  Agrees<Exact<Required<PlanConvertRequest>["recipient"], string>>,
  Agrees<Exact<Required<PlanConvertRequest>["tokenFunding"], Utxo[]>>,
  Agrees<Exact<Required<PlanConvertRequest>["via"], string>>,
];

type _PlanBurnRequest = [
  Agrees<Exact<keyof PlanBurnRequest, "amount" | "currency" | "fee" | "tokenFunding">>,
  Agrees<Exact<OptionalKeys<PlanBurnRequest>, "tokenFunding">>,
  Agrees<Exact<Required<PlanBurnRequest>["amount"], string>>,
  Agrees<Exact<Required<PlanBurnRequest>["currency"], string>>,
  Agrees<Exact<Required<PlanBurnRequest>["fee"], string>>,
  Agrees<Exact<Required<PlanBurnRequest>["tokenFunding"], Utxo[]>>,
];

type _PlanMintRequest = [
  Agrees<Exact<keyof PlanMintRequest, "amount" | "currency" | "fee" | "recipient">>,
  Agrees<Exact<OptionalKeys<PlanMintRequest>, never>>,
  Agrees<Exact<Required<PlanMintRequest>["amount"], string>>,
  Agrees<Exact<Required<PlanMintRequest>["currency"], string>>,
  Agrees<Exact<Required<PlanMintRequest>["fee"], string>>,
  Agrees<Exact<Required<PlanMintRequest>["recipient"], string>>,
];

type _Pending = [
  Agrees<Exact<keyof Pending, "commitmentHex" | "commitmentTxid" | "name" | "pending" | "registrationFee" | "state">>,
  Agrees<Exact<OptionalKeys<Pending>, never>>,
  Agrees<Exact<Required<Pending>["commitmentHex"], string>>,
  Agrees<Exact<Required<Pending>["commitmentTxid"], string>>,
  Agrees<Exact<Required<Pending>["name"], string>>,
  Agrees<Exact<Required<Pending>["pending"], string>>,
  Agrees<Exact<Required<Pending>["registrationFee"], string>>,
  Agrees<Exact<Required<Pending>["state"], "awaitingCommitment" | "readyToRegister">>,
];

type _PlanRegistrationRequest = [
  Agrees<Exact<keyof PlanRegistrationRequest, "minSigs" | "name" | "pinFee" | "primaryAddresses" | "recoveryAuthority" | "referral" | "revocationAuthority" | "salt">>,
  Agrees<Exact<OptionalKeys<PlanRegistrationRequest>, "minSigs" | "pinFee" | "primaryAddresses" | "recoveryAuthority" | "referral" | "revocationAuthority" | "salt">>,
  Agrees<Exact<Required<PlanRegistrationRequest>["minSigs"], number>>,
  Agrees<Exact<Required<PlanRegistrationRequest>["name"], string>>,
  Agrees<Exact<Required<PlanRegistrationRequest>["pinFee"], string>>,
  Agrees<Exact<Required<PlanRegistrationRequest>["primaryAddresses"], string[]>>,
  Agrees<Exact<Required<PlanRegistrationRequest>["recoveryAuthority"], string>>,
  Agrees<Exact<Required<PlanRegistrationRequest>["referral"], string>>,
  Agrees<Exact<Required<PlanRegistrationRequest>["revocationAuthority"], string>>,
  Agrees<Exact<Required<PlanRegistrationRequest>["salt"], string>>,
];

type _PendingRequest = [
  Agrees<Exact<keyof PendingRequest, "pending">>,
  Agrees<Exact<OptionalKeys<PendingRequest>, never>>,
  Agrees<Exact<Required<PendingRequest>["pending"], Pending>>,
];

type _CommitmentWaiting = [
  Agrees<Exact<keyof CommitmentWaiting, "confirmations" | "kind">>,
  Agrees<Exact<OptionalKeys<CommitmentWaiting>, never>>,
  Agrees<Exact<Required<CommitmentWaiting>["confirmations"], number>>,
  Agrees<Exact<Required<CommitmentWaiting>["kind"], "waiting">>,
];

type _CommitmentReady = [
  Agrees<Exact<keyof CommitmentReady, "kind" | "pending">>,
  Agrees<Exact<OptionalKeys<CommitmentReady>, never>>,
  Agrees<Exact<Required<CommitmentReady>["kind"], "ready">>,
  Agrees<Exact<Required<CommitmentReady>["pending"], Pending>>,
];

type _CommitmentReorged = [
  Agrees<Exact<keyof CommitmentReorged, "detail" | "kind">>,
  Agrees<Exact<OptionalKeys<CommitmentReorged>, never>>,
  Agrees<Exact<Required<CommitmentReorged>["detail"], string>>,
  Agrees<Exact<Required<CommitmentReorged>["kind"], "reorged">>,
];

type _CommitmentGone = [
  Agrees<Exact<keyof CommitmentGone, "kind">>,
  Agrees<Exact<OptionalKeys<CommitmentGone>, never>>,
  Agrees<Exact<Required<CommitmentGone>["kind"], "gone">>,
];

type _CommitmentExpired = [
  Agrees<Exact<keyof CommitmentExpired, "expiryHeight" | "kind" | "tip">>,
  Agrees<Exact<OptionalKeys<CommitmentExpired>, never>>,
  Agrees<Exact<Required<CommitmentExpired>["expiryHeight"], number>>,
  Agrees<Exact<Required<CommitmentExpired>["kind"], "expired">>,
  Agrees<Exact<Required<CommitmentExpired>["tip"], number>>,
];

type _Registered = [
  Agrees<Exact<keyof Registered, "feePaid" | "hex" | "identityAddress" | "name" | "txid">>,
  Agrees<Exact<OptionalKeys<Registered>, never>>,
  Agrees<Exact<Required<Registered>["feePaid"], string>>,
  Agrees<Exact<Required<Registered>["hex"], string>>,
  Agrees<Exact<Required<Registered>["identityAddress"], string>>,
  Agrees<Exact<Required<Registered>["name"], string>>,
  Agrees<Exact<Required<Registered>["txid"], string>>,
];

type _Preallocation = [
  Agrees<Exact<keyof Preallocation, "amount" | "recipient">>,
  Agrees<Exact<OptionalKeys<Preallocation>, never>>,
  Agrees<Exact<Required<Preallocation>["amount"], string>>,
  Agrees<Exact<Required<Preallocation>["recipient"], string>>,
];

type _CurrencyDefinition = [
  Agrees<Exact<keyof CurrencyDefinition, "currencies" | "endBlock" | "idImportFees" | "idReferralLevels" | "idRegistrationFees" | "initialSupply" | "kind" | "maxPreconversion" | "minPreconversion" | "name" | "parent" | "preallocations" | "proofProtocol" | "startBlock" | "weights">>,
  Agrees<Exact<OptionalKeys<CurrencyDefinition>, "currencies" | "endBlock" | "idImportFees" | "idReferralLevels" | "idRegistrationFees" | "initialSupply" | "maxPreconversion" | "minPreconversion" | "preallocations" | "proofProtocol" | "weights">>,
  Agrees<Exact<Required<CurrencyDefinition>["currencies"], string[]>>,
  Agrees<Exact<Required<CurrencyDefinition>["endBlock"], number>>,
  Agrees<Exact<Required<CurrencyDefinition>["idImportFees"], string>>,
  Agrees<Exact<Required<CurrencyDefinition>["idReferralLevels"], number>>,
  Agrees<Exact<Required<CurrencyDefinition>["idRegistrationFees"], string>>,
  Agrees<Exact<Required<CurrencyDefinition>["initialSupply"], string>>,
  Agrees<Exact<Required<CurrencyDefinition>["kind"], "token" | "fractional">>,
  Agrees<Exact<Required<CurrencyDefinition>["maxPreconversion"], string[]>>,
  Agrees<Exact<Required<CurrencyDefinition>["minPreconversion"], string[]>>,
  Agrees<Exact<Required<CurrencyDefinition>["name"], string>>,
  Agrees<Exact<Required<CurrencyDefinition>["parent"], string>>,
  Agrees<Exact<Required<CurrencyDefinition>["preallocations"], Preallocation[]>>,
  Agrees<Exact<Required<CurrencyDefinition>["proofProtocol"], number>>,
  Agrees<Exact<Required<CurrencyDefinition>["startBlock"], number>>,
  Agrees<Exact<Required<CurrencyDefinition>["weights"], string[]>>,
];

type _PlanLaunchRequest = [
  Agrees<Exact<keyof PlanLaunchRequest, "definition" | "identity" | "pinLaunchFee">>,
  Agrees<Exact<OptionalKeys<PlanLaunchRequest>, "pinLaunchFee">>,
  Agrees<Exact<Required<PlanLaunchRequest>["definition"], CurrencyDefinition>>,
  Agrees<Exact<Required<PlanLaunchRequest>["identity"], string>>,
  Agrees<Exact<Required<PlanLaunchRequest>["pinLaunchFee"], string>>,
];

type _Launched = [
  Agrees<Exact<keyof Launched, "currencyId" | "hex" | "launchFee" | "startBlock" | "txid">>,
  Agrees<Exact<OptionalKeys<Launched>, never>>,
  Agrees<Exact<Required<Launched>["currencyId"], string>>,
  Agrees<Exact<Required<Launched>["hex"], string>>,
  Agrees<Exact<Required<Launched>["launchFee"], string>>,
  Agrees<Exact<Required<Launched>["startBlock"], number>>,
  Agrees<Exact<Required<Launched>["txid"], string>>,
];

type _Requests = [
  Agrees<Exact<keyof Requests, "ContentRequest" | "ConvertRequest" | "HistoryRequest" | "LoginRequest" | "OfferTermsRequest" | "OffersRequest" | "PendingRequest" | "PlanBurnRequest" | "PlanConvertFromIdentityRequest" | "PlanConvertRequest" | "PlanLaunchRequest" | "PlanMintRequest" | "PlanPublishRequest" | "PlanRegistrationRequest" | "PlanSendFromIdentityRequest" | "PlanSendRequest" | "PlanSendTokenFromIdentityRequest" | "PlanSendTokenRequest" | "SendRequest" | "SignRequest" | "SpendableRequest" | "TakeOfferRequest" | "TokenSendRequest" | "VerifyLoginRequest" | "VerifyRequest">>,
  Agrees<Exact<OptionalKeys<Requests>, never>>,
  Agrees<Exact<Required<Requests>["ContentRequest"], ContentRequest>>,
  Agrees<Exact<Required<Requests>["ConvertRequest"], ConvertRequest>>,
  Agrees<Exact<Required<Requests>["HistoryRequest"], HistoryRequest>>,
  Agrees<Exact<Required<Requests>["LoginRequest"], LoginRequest>>,
  Agrees<Exact<Required<Requests>["OfferTermsRequest"], OfferTermsRequest>>,
  Agrees<Exact<Required<Requests>["OffersRequest"], OffersRequest>>,
  Agrees<Exact<Required<Requests>["PendingRequest"], PendingRequest>>,
  Agrees<Exact<Required<Requests>["PlanBurnRequest"], PlanBurnRequest>>,
  Agrees<Exact<Required<Requests>["PlanConvertFromIdentityRequest"], PlanConvertFromIdentityRequest>>,
  Agrees<Exact<Required<Requests>["PlanConvertRequest"], PlanConvertRequest>>,
  Agrees<Exact<Required<Requests>["PlanLaunchRequest"], PlanLaunchRequest>>,
  Agrees<Exact<Required<Requests>["PlanMintRequest"], PlanMintRequest>>,
  Agrees<Exact<Required<Requests>["PlanPublishRequest"], PlanPublishRequest>>,
  Agrees<Exact<Required<Requests>["PlanRegistrationRequest"], PlanRegistrationRequest>>,
  Agrees<Exact<Required<Requests>["PlanSendFromIdentityRequest"], PlanSendFromIdentityRequest>>,
  Agrees<Exact<Required<Requests>["PlanSendRequest"], PlanSendRequest>>,
  Agrees<Exact<Required<Requests>["PlanSendTokenFromIdentityRequest"], PlanSendTokenFromIdentityRequest>>,
  Agrees<Exact<Required<Requests>["PlanSendTokenRequest"], PlanSendTokenRequest>>,
  Agrees<Exact<Required<Requests>["SendRequest"], SendRequest>>,
  Agrees<Exact<Required<Requests>["SignRequest"], SignRequest>>,
  Agrees<Exact<Required<Requests>["SpendableRequest"], SpendableRequest>>,
  Agrees<Exact<Required<Requests>["TakeOfferRequest"], TakeOfferRequest>>,
  Agrees<Exact<Required<Requests>["TokenSendRequest"], TokenSendRequest>>,
  Agrees<Exact<Required<Requests>["VerifyLoginRequest"], VerifyLoginRequest>>,
  Agrees<Exact<Required<Requests>["VerifyRequest"], VerifyRequest>>,
];

type _DecodedOutput = Agrees<Exact<DecodedOutput, | DecodedPubKeyHash | DecodedPubKey | DecodedReserveOutput | DecodedIdentityPayment | DecodedIdentityPrimary | DecodedIdentityCommitment | DecodedReserveDeposit | DecodedReserveTransfer | DecodedUnsupportedCryptoCondition | DecodedUnknown>>;

// PlanStep<T> is generic; its right-hand side is left unpinned.

type _Content = Agrees<Exact<Content, Record<string, ContentValue[]>>>;

type _TransactionStep = Agrees<Exact<TransactionStep, PlanStep<PlannedTransaction>>>;

type _UpdateStep = Agrees<Exact<UpdateStep, PlanStep<PlannedUpdate>>>;

type _HistoryStep = Agrees<Exact<HistoryStep, PlanStep<HistoryEntry[]>>>;

type _LoginStep = Agrees<Exact<LoginStep, PlanStep<string>>>;

type _VerifyLoginStep = Agrees<Exact<VerifyLoginStep, PlanStep<LoggedIn>>>;

type _SpendableStep = Agrees<Exact<SpendableStep, PlanStep<Funding>>>;

type _ContentStep = Agrees<Exact<ContentStep, PlanStep<Content>>>;

type _OfferSide = Agrees<Exact<OfferSide, OfferSideCurrencies | OfferSideIdentity>>;

type _Demand = Agrees<Exact<Demand, DemandNative | DemandToken>>;

type _OffersStep = Agrees<Exact<OffersStep, PlanStep<Listing[]>>>;

type _OfferTermsStep = Agrees<Exact<OfferTermsStep, PlanStep<OfferTerms>>>;

type _TakeOfferStep = Agrees<Exact<TakeOfferStep, PlanStep<Taken>>>;

type _CommitmentStatus = Agrees<Exact<CommitmentStatus, CommitmentWaiting | CommitmentReady | CommitmentReorged | CommitmentGone | CommitmentExpired>>;

type _RegistrationStep = Agrees<Exact<RegistrationStep, PlanStep<Pending>>>;

type _CommitmentStatusStep = Agrees<Exact<CommitmentStatusStep, PlanStep<CommitmentStatus>>>;

type _RegisteredStep = Agrees<Exact<RegisteredStep, PlanStep<Registered>>>;

type _LaunchStep = Agrees<Exact<LaunchStep, PlanStep<Launched>>>;
