// Generated by `guard_c_exercises_every_registered_request` in
// crates/verus-wasm/src/types.rs. Do not edit: that test rewrites this file
// when run with UPDATE_TYPESCRIPT_PINS=1, and fails when the two disagree.
//
// # Does tsc actually exercise every published request type?
//
// This is guard C. Guards A and B live in Rust: A asserts that what a request
// struct serializes is what its `export interface` declares, B asserts that the
// runtime key list `dto::from_js` rebuilds a caller's object against lists the
// same fields. Both compare field *names*. Neither of them ever looks at the
// types beside those names, so a field declared `number` where the API returns
// a string is invisible to both — only a compiler reading the shipped `.d.ts`
// can see it.
//
// So this file makes tsc read it. `Requests` in the `.d.ts` indexes every
// request interface by name; the mapped type below asks for one value per key:
//
//   * a missing key is TS2741 — a published request nothing exercises;
//   * a field with the wrong type is TS2322;
//   * a field the interface does not declare is TS2353, because these are
//     object literals in a contextually typed position.
//
// The modifiers on the mapped type are what make it complete rather than nearly
// complete, and each of them closes a way for a published type to go unchecked
// while still looking exercised:
//
//   * `-?` on the outer key. A mapped type inherits the modifiers of what it
//     maps over, so without it a `?` on a member of `Requests` would make that
//     request's entry optional here — a published request tsc never asks for.
//     With it, such a member is worse than skipped rather than skipped:
//     `Requests["Foo"]` is `Foo | undefined`, `keyof` that is `never`, and the
//     value demanded for `Foo` is a value of `{}`, checked against nothing. So
//     the Rust meta-guard refuses an optional member of the index outright.
//   * `-?` on the inner keys. Without it, seven of these requests are satisfied
//     by an object that sets only their mandatory fields, and every optional one
//     — `startHeight`, `minExpected`, `salt`, `pinLaunchFee` — goes unchecked,
//     which is exactly the mistyped-field case above.
//   * `NonNullable`. `Required<…>` strips the `?` but not the `| null` beside
//     it, and `null` satisfies `string | null` and `number | null` alike: a
//     field answered with `null` has its declared type checked by nothing.
//     `SignRequest.existing` is the live case — it could be republished as a
//     `number` and no compiler would notice.
//
// # Why the whole file is generated
//
// Guard C is only guard C if it is compiled, and if what is compiled still
// demands something. Nothing in a TypeScript file can assert either about
// itself, so Rust has to. It used to do that by looking for a few byte patterns
// in this file — the mapped type above, and the bytes the file ends with — and
// that was worse than nothing, because it reported coverage the patterns could
// not see through. `// @ts-nocheck` on the first line switches tsc off entirely.
// A `// @ts-ignore` does the same for one line. `} as any;` closes the literal
// so that nothing inside it is checked, and appending an empty object literal
// puts the required ending bytes back. All three left every pattern intact,
// every Rust test green, and `tsc -p` exiting 0.
//
// So there are no patterns. This file — this comment included — is generated
// from `REGISTRY` in crates/verus-wasm/src/types.rs and compared to what is
// checked in byte for byte. A suppression pragma is a difference. A deleted
// request value is a difference. A widened one is a difference. Every
// difference is a failing test, and the test names the command that regenerates
// the file.
//
// The keys are not maintained by hand either: `REGISTRY` comes from
// `dto::request_list!`, the one list of request DTOs, so a new request arrives
// here as a regeneration rather than as an omission someone has to notice.
//
// `tsconfig.json` beside this file decides whether any of this is compiled at
// all, so it is generated and compared the same way — an added `"exclude"` is a
// difference like any other. And `types.rs` `include_str!`s this file, so
// deleting it stops the Rust tests compiling rather than quietly narrowing what
// CI checks.
//
// # What is left to review
//
// That the workflow still runs `tsc -p` at all, on purpose: guarding it would
// mean scanning the workflow's YAML for the shape a human edits, and a scan
// that tokenises differently from what it guards is the bug this design exists
// to stop repeating.
//
// And whether the values below are honest ones. They are object literals, and
// they have to be: an `as` cast, or a `satisfies` on a widened value, makes tsc
// check nothing while the key still appears present. No comparison of bytes can
// tell those apart from an honest literal. What it can do is move the question
// somewhere a reviewer looks — the values live in `EXERCISED_VALUES` in
// types.rs, so widening one is an edit to Rust source rather than a quiet edit
// to a checked-in artefact.
//
// Not compiled into anything: `tsc --noEmit` is the whole test.

import type { Requests } from "../../pkg/verus_wasm.js";

const utxo = {
  txid: "aa".repeat(32),
  vout: 0,
  satoshis: "1000000000",
  scriptPubKey: "76a914" + "22".repeat(20) + "88ac",
};

const exercised: {
  [K in keyof Requests]-?: { [F in keyof Requests[K]]-?: NonNullable<Requests[K][F]> };
} = {
  SendRequest: {
    utxos: [utxo],
    recipients: [{ address: "RQr2cUkF46n7y8WRzDkd1iV9gHusSSQuzX", satoshis: "150000000" }],
    changeAddress: "RQr2cUkF46n7y8WRzDkd1iV9gHusSSQuzX",
    expiryHeight: 1200020,
    feePerKb: "10000",
  },
  TokenSendRequest: {
    utxos: [utxo],
    recipients: [{ address: "RQr2…", currency: "iJhCez…", amount: "100000000" }],
    changeAddress: "RQr2…",
    expiryHeight: 1200020,
    feePerKb: "10000",
  },
  ConvertRequest: {
    utxos: [utxo],
    tokenFunding: [utxo],
    from: "iJhCezBExJHvtyH3fGhNnt2NhU4Ztkf2yq",
    amount: "100000000",
    kind: "reserveToReserve",
    into: "i9nwxtKuVYX4MSbeULLiK2ttVi6rUEhh4X",
    via: "iQihXUcQt8G9TSh58YoM5NRwC1nAyoazFR",
    recipient: "RQr2cUkF46n7y8WRzDkd1iV9gHusSSQuzX",
    refund: "RQr2cUkF46n7y8WRzDkd1iV9gHusSSQuzX",
    chainCurrency: "iJhCezBExJHvtyH3fGhNnt2NhU4Ztkf2yq",
    feeCurrency: "iJhCezBExJHvtyH3fGhNnt2NhU4Ztkf2yq",
    fee: "20000",
    changeAddress: "RQr2cUkF46n7y8WRzDkd1iV9gHusSSQuzX",
    expiryHeight: 1200020,
    feePerKb: "10000",
  },
  SignRequest: {
    identity: "iL9bc…",
    systemId: "iJhCez…",
    blockHeight: 1200000,
    message: "log me in",
    existing: "AYAeAAABQR9hZ2lWaWVQAAAA…",
  },
  VerifyRequest: {
    identity: "iL9bc…",
    systemId: "iJhCez…",
    message: "log me in",
    signature: "AYAeAAAB…",
    primaryAddresses: ["RQr2…"],
    minimumSignatures: 1,
    currentHeight: 1200000,
    maxAgeBlocks: 60,
  },
  PlanSendRequest: {
    to: "RQr2cUkF46n7y8WRzDkd1iV9gHusSSQuzX",
    satoshis: "150000000",
  },
  HistoryRequest: {
    addresses: ["RQr2cUkF46n7y8WRzDkd1iV9gHusSSQuzX"],
    startHeight: 1100000,
    endHeight: 1200000,
  },
  LoginRequest: {
    audience: "https://example.test",
    challenge: "ab".repeat(16),
  },
  VerifyLoginRequest: {
    identity: "iL9bc…",
    signature: "AYAeAAAB…",
    audience: "https://example.test",
    challenge: "ab".repeat(16),
    maxAgeBlocks: 60,
    maxFutureBlocks: 3,
  },
  SpendableRequest: {
    address: "RQr2cUkF46n7y8WRzDkd1iV9gHusSSQuzX",
  },
  ContentRequest: {
    identity: "iL9bc…",
  },
  PlanSendTokenRequest: {
    currency: "iJhCez…",
    to: "RQr2…",
    amount: "100000000",
    tokenUtxos: [utxo],
  },
  PlanSendFromIdentityRequest: {
    identity: "iL9bc…",
    to: "RQr2…",
    satoshis: "150000000",
  },
  PlanSendTokenFromIdentityRequest: {
    identity: "iL9bc…",
    currency: "iJhCez…",
    to: "RQr2…",
    amount: "100000000",
  },
  PlanConvertFromIdentityRequest: {
    identity: "iL9bc…",
    from: "iJhCez…",
    amount: "150000000",
    kind: "intoFractional",
    into: "iQihX…",
    via: "iQihX…",
    recipient: "RQr2…",
    fee: "20010",
  },
  PlanPublishRequest: {
    identity: "iL9bc…",
    key: "vrsc::example.profile",
    values: ["68656c6c6f"],
  },
  OffersRequest: {
    target: "iJhCez…",
    isCurrency: true,
    withOfferBytes: true,
  },
  OfferTermsRequest: {
    offer: "00",
  },
  TakeOfferRequest: {
    offer: "00",
    utxos: [utxo],
    recipient: "RQr2…",
    changeAddress: "RQr2…",
    fee: "20000",
  },
  PlanConvertRequest: {
    from: "iJhCez…",
    amount: "150000000",
    kind: "intoFractional",
    into: "iQihX…",
    via: "iQihX…",
    recipient: "RQr2…",
    fee: "20010",
    minExpected: "149000000",
    tokenFunding: [utxo],
  },
  PlanBurnRequest: {
    currency: "iQihX…",
    amount: "1",
    fee: "20010",
    tokenFunding: [utxo],
  },
  PlanMintRequest: {
    currency: "iQihX…",
    amount: "1",
    recipient: "RQr2…",
    fee: "20010",
  },
  PlanRegistrationRequest: {
    name: "alice",
    primaryAddresses: ["RQr2…"],
    minSigs: 1,
    referral: "bob@",
    revocationAuthority: "iL9bc…",
    recoveryAuthority: "iL9bc…",
    pinFee: "10000000000",
    salt: "ff".repeat(32),
  },
  PendingRequest: {
    pending: {
      state: "awaitingCommitment",
      name: "alice",
      registrationFee: "10000000000",
      commitmentHex: "0400008085202f89",
      commitmentTxid: "bb".repeat(32),
      pending: "opaque-state-blob",
    },
  },
  PlanLaunchRequest: {
    identity: "basket@",
    definition: {
      name: "basket",
      parent: "iJhCez…",
      kind: "fractional",
      startBlock: 1200000,
      endBlock: 1300000,
      initialSupply: "100000000",
      proofProtocol: 2,
      currencies: ["iJhCez…"],
      weights: ["100000000"],
      minPreconversion: ["0"],
      maxPreconversion: ["100000000"],
      preallocations: [{ recipient: "iL9bc…", amount: "100000000" }],
      idRegistrationFees: "10000000000",
      idReferralLevels: 3,
      idImportFees: "10000000000",
    },
    pinLaunchFee: "10000000000",
  },
};

void exercised;
