//! The only place a method name becomes a string.
//!
//! Every request this crate can emit is a variant here. That makes the set
//! finite, greppable and reviewable: adding one is a diff, and the denylist test
//! in `tests/no_wallet_methods.rs` fails if a wallet method ever appears — in
//! this enum or as a literal anywhere else in the crate.
//!
//! **No wallet methods.** Anything that asks a node to hold, use or reveal a key
//! is absent by construction: the SDK signs locally and hands over finished
//! bytes.

/// Defines [`Method`], its wire [`Method::name`], and [`Method::ALL`] from one
/// list.
///
/// This used to be three hand-written lists — the enum, the `name` match and
/// the `ALL` array — kept in sync by hand. `Method::GetAddressMempool` shows
/// what that costs: it landed in the enum and in `name`, but a fourth place,
/// `ALL`, was never touched, and nothing checked that it should have been.
/// `every_variant_is_listed` only ever walked `ALL`, so a variant missing
/// *from* `ALL` was invisible to it — the test could confirm entries were
/// correct, never that the list was complete. Generating all three from this
/// one macro removes the fourth place: a variant that exists has to be typed
/// here once, and `ALL` is built from the exact same tokens as the enum, so
/// there is nothing left for them to disagree about.
macro_rules! methods {
    ($($(#[$meta:meta])* $variant:ident => $name:literal),+ $(,)?) => {
        /// A JSON-RPC method this crate is allowed to call.
        ///
        /// Deliberately private to the crate.
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub(crate) enum Method {
            $($(#[$meta])* $variant),+
        }

        impl Method {
            /// The wire name.
            pub(crate) const fn name(self) -> &'static str {
                match self {
                    $(Method::$variant => $name),+
                }
            }

            /// Every variant, generated from the same list as the enum and
            /// [`name`](Method::name) above. There is no separate,
            /// hand-maintained array left to fall out of sync with the enum.
            const ALL: &'static [Method] = &[$(Method::$variant),+];
        }
    };
}

methods! {
    // Chain
    GetInfo => "getinfo",
    GetBlockCount => "getblockcount",
    GetBestBlockHash => "getbestblockhash",
    GetBlockHash => "getblockhash",
    GetBlock => "getblock",
    // Funds
    GetAddressUtxos => "getaddressutxos",
    GetAddressBalance => "getaddressbalance",
    GetAddressDeltas => "getaddressdeltas",
    GetAddressMempool => "getaddressmempool",
    // Policy
    GetCurrency => "getcurrency",
    GetCurrencyState => "getcurrencystate",
    ListCurrencies => "listcurrencies",
    GetCurrencyConverters => "getcurrencyconverters",
    EstimateConversion => "estimateconversion",
    EstimateFee => "estimatefee",
    GetIdentity => "getidentity",
    GetIdentityHistory => "getidentityhistory",
    GetIdentityContent => "getidentitycontent",
    GetVdxfId => "getvdxfid",
    GetOffers => "getoffers",
    VerifyMessage => "verifymessage",
    GetRawMempool => "getrawmempool",
    // Transactions
    GetRawTransaction => "getrawtransaction",
    DecodeRawTransaction => "decoderawtransaction",
    /// The one method that changes anything, and it takes bytes that were
    /// already signed elsewhere.
    SendRawTransaction => "sendrawtransaction",
}

impl Method {
    /// Whether calling this can change state anywhere.
    ///
    /// Exactly one method can, which is the property the read/write split in
    /// [`crate::client`] rests on — and, since [`Cassette`](crate::Cassette)
    /// landed, rather more than that: a request this reports as a read is
    /// **recorded and handed to a driver to post**, and a driver posts what it
    /// is told.
    ///
    /// # Why every read is written out
    ///
    /// `matches!(self, Method::SendRawTransaction)` says the same thing in one
    /// line and fails to the wrong side. A write method added later without a
    /// case here would silently be a read: recorded rather than refused, then
    /// posted once per round — up to the driver's round cap — by every caller
    /// following the documented "post `ask` verbatim" contract.
    ///
    /// Listing the reads makes that a compile error instead. Same reason the
    /// `name` match generated by `methods!` is exhaustive, applied to the arm
    /// where being wrong costs money rather than a label.
    pub(crate) const fn is_write(self) -> bool {
        match self {
            Method::SendRawTransaction => true,

            Method::GetInfo
            | Method::GetBlockCount
            | Method::GetBestBlockHash
            | Method::GetBlockHash
            | Method::GetBlock
            | Method::GetAddressUtxos
            | Method::GetAddressBalance
            | Method::GetAddressDeltas
            | Method::GetAddressMempool
            | Method::GetCurrency
            | Method::GetCurrencyState
            | Method::ListCurrencies
            | Method::GetCurrencyConverters
            | Method::EstimateFee
            | Method::EstimateConversion
            | Method::GetIdentity
            | Method::GetIdentityHistory
            | Method::GetIdentityContent
            | Method::GetVdxfId
            | Method::GetOffers
            | Method::VerifyMessage
            | Method::GetRawMempool
            | Method::GetRawTransaction
            | Method::DecodeRawTransaction => false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Which methods write, over the whole enum.
    ///
    /// Note what this can and cannot do. It fails when a *correctly* flagged
    /// second write is added, which is a prompt to think rather than a defect
    /// found. It cannot fail when a flag is **forgotten** — the dangerous
    /// direction — because a method missing from `ALL` is invisible here.
    /// That direction is guarded by `is_write` being an exhaustive match, so a
    /// new variant does not compile until it is classified.
    #[test]
    fn only_one_method_writes() {
        let writes: Vec<_> = Method::ALL.iter().filter(|m| m.is_write()).collect();
        assert_eq!(writes, vec![&Method::SendRawTransaction]);
    }

    /// `ALL` has to actually be all of them, or every test that iterates it
    /// proves less than it looks like it does.
    ///
    /// This used to be the guard: a loop over `ALL` checking names are
    /// non-empty, plus a hand-pinned count. Neither can see a variant that
    /// `ALL` never mentions — `Method::GetAddressMempool` was in the enum and
    /// in `name`, absent from `ALL`, and this test passed anyway because the
    /// count had been pinned to match the omission rather than the enum.
    /// `ALL` is no longer a hand-written array to fall behind: `methods!`
    /// builds the enum, `name` and `ALL` from one list, so a variant present
    /// in the enum is present in `ALL` by construction. What is left to check
    /// is the ordinary kind of bug — a typo'd or duplicated name.
    #[test]
    fn every_variant_is_listed() {
        for method in Method::ALL {
            assert!(!method.name().is_empty());
        }
        assert_eq!(Method::ALL.len(), 25);
    }

    #[test]
    fn every_name_is_distinct() {
        let mut names: Vec<_> = Method::ALL.iter().map(|m| m.name()).collect();
        names.sort_unstable();
        let count = names.len();
        names.dedup();
        assert_eq!(names.len(), count);
    }
}

/// One method this crate is able to call.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CallableMethod {
    /// The JSON-RPC method name.
    pub name: &'static str,
    /// Whether calling it can change state anywhere.
    pub writes: bool,
}

/// Every JSON-RPC method this crate is able to emit.
///
/// The crate docs claim a node is never asked to hold or use a key. This is
/// that claim in machine-readable form: a consumer with its own policy — an
/// audit, a proxy allowlist, a compliance check — can assert against this list
/// rather than trusting the prose, and will notice if a later version adds
/// something.
///
/// ```
/// let methods = verus_rpc::callable_methods();
///
/// // Exactly one method changes anything, and it takes bytes signed elsewhere.
/// let writes: Vec<_> = methods.iter().filter(|m| m.writes).collect();
/// assert_eq!(writes.len(), 1);
/// assert_eq!(writes[0].name, "sendrawtransaction");
///
/// // Nothing here asks a node for, or about, a key.
/// assert!(!methods.iter().any(|m| m.name.contains("wallet")));
/// ```
pub fn callable_methods() -> Vec<CallableMethod> {
    Method::ALL
        .iter()
        .map(|method| CallableMethod {
            name: method.name(),
            writes: method.is_write(),
        })
        .collect()
}
